name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

        #hay un error en la autenticacion por alguna razon, si termina y sube las imagenes se agrego el true para ignorar...
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}  || true

      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api:"$GITHUB_SHA" ./api
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web:"$GITHUB_SHA" ./web
          docker push ${{ secrets.DOCKER_USERNAME }}/api:"$GITHUB_SHA"
          docker push ${{ secrets.DOCKER_USERNAME }}/web:"$GITHUB_SHA"

      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Login to AWS 
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

#Terraform steps
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Apply
        id:   apply
        env:
         TF_VAR_ec2_name:  "${{ github.event.inputs.ec2-name }}"
        run: |
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve


